version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
    volumes: 
      - ./nginx/sites/:/etc/nginx/sites-available
    depends_on: 
      - rocket
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend

  rocket:
    build:
      context: ./rocket
    environment:
      - DEPLOY_METHOD=docker
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - HOME=/tmp
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - Accounts_AvatarStorePath=/app/uploads
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mongo-replica
    networks:
      - frontend
      - backend

  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-replica:
    build: ./mongo-replica
    depends_on:
      - mongo
    networks:
      - backend
